# Generated by Django 3.2.6 on 2023-04-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreastCancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clump_thickness', models.FloatField()),
                ('uniformity_of_cell_size', models.FloatField()),
                ('uniformity_of_cell_shape', models.FloatField()),
                ('marginal_adhesion', models.FloatField()),
                ('single_epithelial_cell_size', models.FloatField()),
                ('bare_nuclei', models.FloatField()),
                ('bland_chromatin', models.FloatField()),
                ('normal_nucleoli', models.FloatField()),
                ('mitoses', models.FloatField()),
                ('result', models.BooleanField(null=True)),
            ],
        ),
    ]
